---
- name: Play to register an output
  hosts: allDC
  tasks:
    - name: run whoami on remote box
      command: whoami
      register: cmd_out
    - debug:
        var: cmd_out.stdout
 #       var: cmd_out
...
