###  Just a nested loop
---
- name: Check the looping structure...joe->clientdb, joe->emploeedb etc....we test to create 2 users with 3 differnt databases..This is Nested Loop
  hosts: serverb.lab.example.com
  tasks:
    - name: Create the users
      debug: 
        msg: " this is {{item[0]}} from {{item[1]}}"

      with_nested: 
        - [ 'joe', 'jane' ]
        - [ 'clientdb', 'employeedb', 'providerdb' ]

