---
# This playbook patches dirty cow

- hosts: redhat centos ubuntu
  gather_facts: true
  serial: 1
  become: yes
  max_fail_percentage: 0
  tasks:
    - name:  Install telnet 
      yum:
        name: telnet 
        state: absent  
      register: output 

    - name: reboot
      shell: shutdown -r now
      when: output.changed
      register: reboot

    - name: Wait for the server to come back
      wait_for:
        host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
        delay: 60
        state: started
        search_regex: OpenSSH
        port: 22
      become: false
      when: reboot.changed
      delegate_to: localhost
