---
- name: install and configure the web services on Centos
  hosts: centos
  vars:
    firewall: firewalld

  tasks:     
    - name: include variable file
      include_vars: vars/main.yml
    - name: include the tasks
      include: tasks/main.yml

    - name: install firewalld
      yum:
        name: "{{ firewall }}"
        state: latest

    - name: start the firewalld
      service:
        name: "{{ firewall }}"
        state: started
        enabled: true

    - name: Open Firewall port
      firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true

    - name: Create index.html
      copy:
        content: "{{ insble_fqdn}} {{{ ansible_default_ipv4.address }}} This my first web page from ansible playbook jao Ho \n"
        dest: "{{web_root }}/index.html"


